version: "3.9"
 
########################### NETWORKS
networks:
  default:
    driver: bridge
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: bond0 # using ifconfig or ip a to view interface name
    ipam:
      config:
      - subnet: "192.168.12.0/24"
        ip_range: "192.168.12.254/32"
        gateway: "192.168.12.1"
########################### SERVICES
services:
  # AdGuard Home - DNS AdBlocking
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: 192.168.12.254 # IP address inside the defined range
    ports:
      - 53:53/udp
      - 67:67/udp 
      - 68:68/tcp 
      - 68:68/udp 
      - 80:80/tcp 
      - 443:443/tcp 
      - 853:853/tcp 
      - 3000:3000/tcp 
    volumes:
      - $DOCKERDIR/appdata/adguardhome/conf:/opt/adguardhome/conf
      - $DOCKERDIR/appdata/adguardhome/work:/opt/adguardhome/work
      #- $DOCKERDIR/shared/certs/example.com:/certs # optional: if you have your own SSL certs
